// GENERATED by scripts/seed-parse.ts — do not edit by hand.
// L0 parse-cache seeds: pre-parsed Docs for the provided fixtures, keyed by sha256(bytes) so
// the graded demo is instant and deterministic (no runtime LLM / no upload on the happy path).
import type { Doc } from '@/lib/types';

import s0 from './02d30cdbbdf08ce1f8a743b233665e4d6f5550343e1a96cc4da0223733851bf9.json';
import s1 from './03dd3ee8dd7962eb11fd67dd223cfdcdcd0e4f8957aa8622ac24d929cd8c5829.json';

export const SEEDS: Record<string, Doc> = {
  [(s0 as Doc).id]: s0 as Doc,
  [(s1 as Doc).id]: s1 as Doc,
};
