// GENERATED by scripts/seed-renders.ts — do not edit by hand.
// Hashes whose "Original PDF" page images are committed under public/pages/<hash>/<n>.jpg,
// pre-rendered so the seeded demo's Original view is instant and needs no source bytes server-side.
export const RENDERED: Record<string, { pages: number; scale: number }> = {
  '03dd3ee8dd7962eb11fd67dd223cfdcdcd0e4f8957aa8622ac24d929cd8c5829': { pages: 8, scale: 1.5 },
};
