// SEED RENDERS — pre-bake the "Original PDF" view for committed fixtures.
//
// Renders each page of a fixture to public/pages/<sha256>/<n>.jpg and regenerates the manifest
// src/parse-cache/renders.ts. Committing these small JPEGs (easy.pdf's 8 pages ≈ 0.8MB) makes the
// seeded/graded demo's Original view instant and byte-free (the server never has the source PDF on
// the seed-cache path). This is SEPARATE from `npm run seed` on purpose: it does NOT touch the
// parse-cache Doc JSON and makes NO LLM call — rendering is pure mupdf/CPU.
//
// Run:  npm run seed:renders                # default: easy.pdf (the sample / the bar)
//       npm run seed:renders -- easy.pdf hard.pdf
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';
import { sha256 } from '@/parse/hash';
import { renderAllPages, RENDER_SCALE } from '@/parse/render';

const FIXTURES = '/Users/john/strala/workspaces/ws_8ab97d2dec3e/ExampleProposals/proposals';
const PAGES_DIR = resolve('public/pages');
const MANIFEST = resolve('src/parse-cache/renders.ts');

const args = process.argv.slice(2);
const targets = args.length ? args : ['easy.pdf'];

for (const t of targets) {
  const path = t.includes('/') ? t : join(FIXTURES, t);
  const filename = basename(path);
  const bytes = new Uint8Array(readFileSync(path));
  const hash = sha256(bytes);
  process.stdout.write(`rendering ${filename} (${hash.slice(0, 8)}…) `);
  const pages = renderAllPages(bytes, { scale: RENDER_SCALE });
  const dir = join(PAGES_DIR, hash);
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  pages.forEach((buf, i) => writeFileSync(join(dir, `${i + 1}.jpg`), buf));
  const kb = Math.round(pages.reduce((s, b) => s + b.length, 0) / 1024);
  console.log(`→ ${pages.length} pages · ${kb}KB`);
}

// Regenerate the manifest by scanning whatever page sets are committed under public/pages/.
const hashes = existsSync(PAGES_DIR)
  ? readdirSync(PAGES_DIR, { withFileTypes: true })
      .filter((d) => d.isDirectory() && /^[0-9a-f]{64}$/.test(d.name))
      .map((d) => d.name)
      .sort()
  : [];
const entries = hashes
  .map((h) => {
    const count = readdirSync(join(PAGES_DIR, h)).filter((f) => /^\d+\.jpg$/.test(f)).length;
    return `  '${h}': { pages: ${count}, scale: ${RENDER_SCALE} },`;
  })
  .join('\n');
const manifest =
  `// GENERATED by scripts/seed-renders.ts — do not edit by hand.\n` +
  `// Hashes whose "Original PDF" page images are committed under public/pages/<hash>/<n>.jpg,\n` +
  `// pre-rendered so the seeded demo's Original view is instant and needs no source bytes server-side.\n` +
  `export const RENDERED: Record<string, { pages: number; scale: number }> = {\n` +
  `${entries}\n};\n`;
writeFileSync(MANIFEST, manifest);
console.log(`\nwrote ${hashes.length} render set(s) + regenerated renders.ts`);
